---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mikhmon-data-pvc
  namespace: mikhmon-app
  labels:
    app: mikhmon-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
